name: lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: mumoshu/conflint:latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: conflint
      run: |
        set -vx
        pwd
        ls -lah
        apt-get update -y
        apt-get install git -y
        git rev-parse --show-prefix
        export CONFLINT_LOG=DBEUG
        conflint run -efm "%f:%l:%c: %m"
        kubeval flux/deployment.yaml
        kubeval flux/deployment.yaml -o json
        conflint run -efm "%f:%l:%c: %m" | reviewdog -efm="%f:%l:%c: %m" -reporter=github-pr-check -tee
